### ISSUE TITLE
Release 5.0.1 not in latest release tar/zip

### ISSUE THREAD

**Issue by bmhkb4** [concourse/concourse-bosh-release#23]
Hi there!

# Bug Report

When trying to reference the 5.0+ [released artifacts](https://github.com/concourse/concourse-bosh-release/releases/tag/v5.0.1) for a Bosh deployed Concourse, no 5.0+ releases exist and the deployment fails.

* Concourse version: 5.0+
* Deployment type (BOSH/Docker/binary): BOSH

```
# ls -lrt ~/concourse-bosh-release-5.0.1/releases/concourse/concourse-5*
ls: cannot access /root/concourse-bosh-release-5.0.1/releases/concourse/concourse-5*: No such file or directory
# ls -lrt ~/concourse-bosh-release-5.0.1/releases/concourse/concourse-4*
-rw-rw-r-- 1 root root 8191 Mar 22 15:53 /root/concourse-bosh-release-5.0.1/releases/concourse/concourse-4.2.3.yml
-rw-rw-r-- 1 root root 8191 Mar 22 15:53 /root/concourse-bosh-release-5.0.1/releases/concourse/concourse-4.2.2.yml
-rw-rw-r-- 1 root root 8191 Mar 22 15:53 /root/concourse-bosh-release-5.0.1/releases/concourse/concourse-4.2.1.yml
-rw-rw-r-- 1 root root 8191 Mar 22 15:53 /root/concourse-bosh-release-5.0.1/releases/concourse/concourse-4.2.0.yml
-rw-rw-r-- 1 root root 7983 Mar 22 15:53 /root/concourse-bosh-release-5.0.1/releases/concourse/concourse-4.1.0.yml
-rw-rw-r-- 1 root root 7984 Mar 22 15:53 /root/concourse-bosh-release-5.0.1/releases/concourse/concourse-4.0.0.yml
```

**Comment by vito** [comment]
The tags point to the commit that resulted in the release, not the commit that checks in the artifacts, as that commit would then have unreleased commits behind it.

Tags aren't necessary when uploading via YAML in the release repo, since you're referencing them via their YAML file anyway, and the contents of the repo doesn't matter. If you'd like to just consume releases as they come out, I would use [bosh.io](https://bosh.io/releases/github.com/concourse/concourse-bosh-release?all=1) instead.

**Comment by bmhkb4** [comment]
Thanks for the response.  Bummer, bosh.io is blocked in China (hosted on aws).  Trying to get around that legally =(
