### ISSUE TITLE
Patch release v5.2.1?

### ISSUE THREAD

**Issue by bodymindarts** [concourse/concourse-bosh-release#33]
Would it be possible to cut a patch release containing the fix of https://github.com/concourse/concourse-bosh-release/pull/31? Would be highly appreciated.

**Comment by vito** [comment]
Related: #21 - I don't really want to force a new release of all of Concourse because of this alone, though we'll probably do another release pretty soon anyway.

For my own understanding, what is the impact of not having the change, given that we didn't handle systemd specially at all in versions prior to v5.2?

**Comment by deniseyu** [comment]
hey @bodymindarts this should be in the latest set of releases now! @vito do you wanna keep this thread open re: your systemd question?

**Comment by bodymindarts** [comment]
yes its fixed thank you!
